# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7bb608d535aa329e7df99ce0c851c350167d0c00757b0ec50443e412833c50b425a5d359e2229c271381e5204405cacc3ce42397e9fa1ee2966ff2d2ce75302

test:
  secret_key_base: 8ebc2b6ee11de50178501037bdf928263bc6537f6e1703f39556ec19da4d9abec43d65ff2f81866bf4e64e1397c2e9f45b2e64b40d4bcc0f36acdf4890916f19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
